apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8092
      targetPort: 8092
  selector:
    app: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: "johnm60/node-app-cosmos:latest"
          ports:
            - containerPort: 8092
          env:
            - name: PORT
              value: "8092"
            - name: CONNECTION_STRING
              value: "<your-cosmos-mongodb-connection-string>"
